export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"

export const LOGOUT_USER = "LOGOUT_USER"

export const GET_PROFILE_USER_JWT_SUCCESS = "GET_PROFILE_USER_JWT_SUCCESS"
export const GET_PROFILE_USER_JWT_FAILURE = "GET_PROFILE_USER_JWT_FAILURE"

export const GET_ALL_USER_LIST_SUCCESS = "GET_ALL_USER_LIST_SUCCESS"
export const GET_ALL_USER_LIST_FAILURE = "GET_ALL_USER_LIST_FAILURE"

export const GET_PROFILE_USER_ID_SUCCESS = "GET_PROFILE_USER_ID_SUCCESS"
export const GET_PROFILE_USER_ID_FAILURE = "GET_PROFILE_USER_ID_FAILURE"

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

export const UPDATE_STATUS_USER_SUCCESS = "UPDATE_STATUS_USER_SUCCESS"
export const UPDATE_STATUS_USER_FAILURE = "UPDATE_STATUS_USER_FAILURE"

export const REQUEST_ADD_FRIEND_SUCCESS = "REQUEST_ADD_FRIEND_SUCCESS"
export const REQUEST_ADD_FRIEND_FAILURE = "REQUEST_ADD_FRIEND_FAILURE"

export const UNFRIEND_SUCCESS = "UNFRIEND_SUCCESS"
export const UNFRIEND_FAILURE = "UNFRIEND_FAILURE"

export const ACCEPT_REQUEST_ADD_FRIEND_SUCCESS = "ACCEPT_REQUEST_ADD_FRIEND_SUCCESS"
export const ACCEPT_REQUEST_ADD_FRIEND_FAILURE = "ACCEPT_REQUEST_ADD_FRIEND_FAILURE"

export const REFUSE_REQUEST_ADD_FRIEND_SUCCESS = "REFUSE_REQUEST_ADD_FRIEND_SUCCESS"
export const REFUSE_REQUEST_ADD_FRIEND_FAILURE = "REFUSE_REQUEST_ADD_FRIEND_FAILURE"

export const GET_ALL_REQUEST_ADD_FRIEND_SUCCESS = "GET_ALL_REQUEST_ADD_FRIEND_SUCCESS"
export const GET_ALL_REQUEST_ADD_FRIEND_FAILURE = "GET_ALL_REQUEST_ADD_FRIEND_FAILURE"

export const GET_ALL_SEND_REQUEST_ADD_FRIEND_SUCCESS = "GET_ALL_SEND_REQUEST_ADD_FRIEND_SUCCESS"
export const GET_ALL_SEND_REQUEST_ADD_FRIEND_FAILURE = "GET_ALL_SEND_REQUEST_ADD_FRIEND_FAILURE"

export const GET_ALL_LIST_FRIEND_SUCCESS = "GET_ALL_LIST_FRIEND_SUCCESS"
export const GET_ALL_LIST_FRIEND_FAILURE = "GET_ALL_LIST_FRIEND_FAILURE"


