export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE"
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS"

export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE"
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS"

export const DELETE_POSTS_FAILURE = "DELETE_POSTS_FAILURE"
export const DELETE_POSTS_SUCCESS = "DELETE_POSTS_SUCCESS"

export const UPDATE_POSTS_FAILURE = "UPDATE_POSTS_FAILURE"
export const UPDATE_POSTS_SUCCESS = "UPDATE_POSTS_SUCCESS"

export const GET_POSTS_BY_ID_FAILURE = "GET_POSTS_BY_ID_FAILURE"
export const GET_POSTS_BY_ID_SUCCESS = "GET_POSTS_BY_ID_SUCCESS"

export const GET_USER_POSTS_FAILURE = "GET_USER_POSTS_FAILURE"
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS"

export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE"
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"

export const LIKE_COMMENT_FAILURE = "LIKE_COMMENT_FAILURE"
export const LIKE_COMMENT_SUCCESS = "LIKE_COMMENT_SUCCESS"

export const GET_LIKE_POST_FAILURE = "GET_LIKE_POST_FAILURE"
export const GET_LIKE_POST_SUCCESS = "GET_LIKE_POST_SUCCESS"

export const COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE"
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS"

export const REPLIES_COMMENT_FAILURE = "REPLIES_COMMENT_FAILURE"
export const REPLIES_COMMENT_SUCCESS = "REPLIES_COMMENT_SUCCESS"

export const HIDDEN_POST_FAILURE = "HIDDEN_POST_FAILURE"
export const HIDDEN_POST_SUCCESS = "HIDDEN_POST_SUCCESS"

export const HIDDEN_USER_FAILURE = "HIDDEN_USER_FAILURE"
export const HIDDEN_USER_SUCCESS = "HIDDEN_USER_SUCCESS"

export const BOOKMARK_POST_FAILURE = "BOOKMARK_POST_FAILURE"
export const BOOKMARK_POST_SUCCESS = "BOOKMARK_POST_SUCCESS"

export const GET_ALL_BOOKMARK_POST_FAILURE = "GET_ALL_BOOKMARK_POST_FAILURE"
export const GET_ALL_BOOKMARK_POST_SUCCESS = "GET_ALL_BOOKMARK_POST_SUCCESS"

export const DELETE_BOOKMARK_POST_FAILURE = "DELETE_BOOKMARK_POST_FAILURE"
export const DELETE_BOOKMARK_POST_SUCCESS = "DELETE_BOOKMARK_POST_SUCCESS"

export const CLEAR_POST_SUCCESS = "CLEAR_POST_SUCCESS"


